### ISSUE TITLE
파일 추가 후 PR

### ISSUE THREAD

**Issue by s21900156** [Juheon17/OSS_first#3]
파일을 추가하고 PR하는 것은 안되는 건가요? 
제가 파일을 한 번 추가해보고 commit을 하려고 하는데 파일 바뀐 것이 없다고 하네요.
수정한 후에 PR하는 것은 되는데 이거는 안되는 것 같네요.
그 이유를 잘 모르겠네요,,혹시 아시면 알려주세요.

**Comment by Juheon17** [comment]
Git에서 fork 떠서하신건가요? Windows용 메일에서 발송된 메일입니다. 보낸 사람: s21900156보낸 날짜: 2022년 4월 30일 토요일 오후 8:51받는 사람: Juheon17/OSS_first참조: Subscribed제목: [Juheon17/OSS_first] 파일 추가 후 PR (Issue #3) 파일을 추가하고 PR하는 것은 안되는 건가요?제가 파일을 한 번 추가해보고 commit을 하려고 하는데 파일 바뀐 것이 없다고 하네요.수정한 후에 PR하는 것은 되는데 이거는 안되는 것 같네요.그 이유를 잘 모르겠네요,,혹시 아시면 알려주세요.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by s21900156** [comment]
아,,이게 PR을 받기 전에 고치면 알아서 되는 것 같네요.이해했습니다. 감사합니ㄷ~
